Feat/88 duplicates
Pandora-IsoMemo/iso-app pull request #100
Opened 2023-02-10 10:37 UTC by f-lukas

## Version 23.02.3

### Updates
- Option to decide if column with duplicate rows is added
- Option to ignore spaces during duplicate detection
- Option to specify a string that is used for duplicate detection

2023-02-10 10:57 UTC, f-lukas commented
@arunge could you please check if the new features work as expected? Thanks!

2023-02-14 14:23 UTC, arunge requested changes
Please check the white spaces option, the other two new options are working. :+1:

2023-02-14 14:23 UTC, arunge commented on NEWS.md
> +- Option to ignore spaces during duplicate detection
Could there be a bug here?

Without "Ignore Spaces" (1):
![image](https://user-images.githubusercontent.com/16759098/218761124-294bac9e-39a5-43bc-a11f-dcfc81a97e9b.png)

With "Ignore Spaces" (2):
![image](https://user-images.githubusercontent.com/16759098/218761559-560a0ffb-8c61-46d0-8c60-01eea34c8200.png)

2023-02-14 14:23 UTC, arunge commented on R/01-createDuplicateModal.R
> +                Optional you can specify a specific string. If you do so, rows that contain this string in the selected column are marked as duplicate.
```suggestion
                Optionally, you can specify a specific string. If you do so, rows that contain this string in the selected column are marked as duplicate.
```

2023-02-14 14:23 UTC, arunge commented on R/01-createDuplicateModal.R
>                  You can also enter negative numbers, which will result in rounding to the power of ten, e.g. the value -2 rounds to the nearest hundred.
```suggestion
                You can also enter negative numbers, which will result in rounding to the power of ten, e.g. the value -2 rounds to the nearest hundred.<br><br>
```

2023-02-14 15:51 UTC, f-lukas commented
Very good that you noticed it. The combination of specifying a string and ignoring spaces didn't work because I only removed the spaces in the data and not in the specified string. It should now work.

2023-02-14 16:23 UTC, arunge reviewed
The issue with the white spaces is fixed now. :+1: 

There is something else: In the sidebar one can specify the columns to be displayed within the app:

![image](https://user-images.githubusercontent.com/16759098/218793817-2b5d1eca-f299-4321-8e14-cc14957e655c.png)

In the pop up there are always all columns shown:

![image](https://user-images.githubusercontent.com/16759098/218794195-a0f58c63-b32b-40a9-a67d-76157b2ad592.png)

Maybe this is even a feature:
- there are less reactive dependencies between the sidebar selection and the duplicate search
- for me it does not to be a disadvantage to display the full data within the duplicate search. 

So we can even keep this as it is now. What do you think?

However, there seems to be an issue with the cutting of strings, it is not working always:

![image](https://user-images.githubusercontent.com/16759098/218796283-29bee560-0f4e-4b52-84d4-c533360c8ba6.png)

Can you check this? If this is a general issue and we should adjust the function in DataTools, please let me know.

Possibly this has to do with: https://github.com/Pandora-IsoMemo/iso-app/pull/101#issuecomment-1429941764
I am checking now.

2023-02-14 16:32 UTC, f-lukas commented
The reason for this is the same as in https://github.com/Pandora-IsoMemo/iso-app/pull/101#issuecomment-1429941764, where I just implemented a workaround. It is not a bug but `cutAllLongStrings` only cuts character columns but not factor. There are quite many factor columns in the IsoMemo data sets. Maybe we can add the option to convert factor to character before cutting in `cutAllLongStrings`. What do you think?

2023-02-14 16:32 UTC, arunge approved these changes
Regarding:

> Can you check this? If this is a general issue and we should adjust the function in DataTools, please let me know.

We will solve this problem within another issue. Thus this PR is approved.

2023-02-16 13:57 UTC, merged