DetectDuplicates: Option to decide whether to keep the first or last duplicate row
Pandora-IsoMemo/iso-app pull request #114
Opened 2023-03-09 15:02 UTC by f-lukas

https://github.com/Pandora-IsoMemo/iso-app/issues/88

2023-03-13 20:03 UTC, arunge requested changes
Das "m" ist vermutlich versehentlich reingerutscht, ansonsten war alles ok. :+1:

2023-03-13 20:03 UTC, arunge commented on NEWS.md
> +m
```suggestion

```

2023-03-14 09:30 UTC, f-lukas commented
> Das "m" ist vermutlich versehentlich reingerutscht, ansonsten war alles ok. +1

@arunge danke. Habe es korrigiert.

2023-03-14 09:48 UTC, arunge approved these changes

2023-03-14 16:26 UTC, merged