Feature/135 apply functions from datatools
Pandora-IsoMemo/iso-app pull request #149
Opened 2023-05-03 10:12 UTC by jan-abel-inwt

2023-05-09 14:05 UTC, arunge requested changes
Could you please merge the changes from `main` into this branch? Everything else looks ok. :+1: 

![image](https://github.com/Pandora-IsoMemo/iso-app/assets/16759098/011129bc-e417-45dc-9de6-190850b89072)

2023-05-09 16:03 UTC, jan-abel-inwt commented
> Could you please merge the changes from `main` into this branch? Everything else looks ok. +1 https://github.com/Pandora-IsoMemo/iso-app/network ![image](https://user-images.githubusercontent.com/16759098/237120006-011129bc-e417-45dc-9de6-190850b89072.png)

Done.

2023-05-09 19:02 UTC, arunge requested changes
@jan-abel-inwt Please let us discuss the issue tomorrow (and rethink the case together) before you start changing something

2023-05-09 19:02 UTC, arunge commented on R/01-isomemoAPI.R
> -  getMappingAPI()
analog to `getDatabaseList`

2023-05-09 19:02 UTC, arunge commented on R/01-isomemoAPI.R
> -  isoData <- getRemoteDataAPI(db = db)
analog to `getDatabaseList`

2023-05-10 08:37 UTC, arunge commented
As just discussed, forget the above, just add the lines 
```R
if (Sys.getenv("API_BASE_URL") != "") {
    apiBaseURL <- Sys.getenv("API_BASE_URL")
  } else {
    apiBaseURL <- Sys.getenv("API_BASE_URL_DEFAULT")
}
```
instead of 
```R
apiBaseURL <- Sys.getenv("API_BASE_URL")
```
to the DataTools function! :slightly_smiling_face: 

Then the error should be fixed.

2023-05-10 09:34 UTC, arunge submitted a review, later dismissed
With the new version 23.04.3.1 of DataTools the issue is solved.

2023-05-10 10:40 UTC, arunge approved these changes
:+1:

2023-05-10 10:40 UTC, merged