altitude operations
Pandora-IsoMemo/iso-app pull request #191
Opened 2023-11-09 15:37 UTC by mgross

Now it is possible to create altitude/elevation maps (data comes from package elevatr):
![grafik](https://github.com/Pandora-IsoMemo/iso-app/assets/5138071/58aa0b42-ab96-4943-adfe-a4d2b81fec1e)

![grafik](https://github.com/Pandora-IsoMemo/iso-app/assets/5138071/c4204a9c-a943-4d24-ac07-d09ba68b837f).

Also custom maps are now possible (user must provide longitude (x), latitude (y) and value (x) data; note that each possible x-y combination must exist, i.e. full data matrix):
![grafik](https://github.com/Pandora-IsoMemo/iso-app/assets/5138071/a525803b-bcf4-4ace-9cf3-3dfb78714b35)

Weighting inside LocatoR with said altitude map (or any other map) is possible. 
We have the option to set negative weighting values to 0 and to apply inverse exponential decay weighting. In the latter case, we can apply a halftime. This can make sense when we weight with altitude for example:
 For a half-time of 1000m, locations with 1000 altitude get half the probability, with 2000m 1/4 of the probability and so forth.

Using Lives 13C data with 13C -18/1 as point gives this without weighting:
![grafik](https://github.com/Pandora-IsoMemo/iso-app/assets/5138071/e0bad6e1-c61b-43db-9cb7-aeab6f7d11d8)
However with weighting, higher altitudes are downweighted:
![grafik](https://github.com/Pandora-IsoMemo/iso-app/assets/5138071/15777a9c-1e13-4500-a6d3-9a4aadc97b94)
With negative values set to zero weight oceans and areas below sealevel get 0 weight:
![grafik](https://github.com/Pandora-IsoMemo/iso-app/assets/5138071/54be4012-d28d-4838-9893-d16071d6602b)

2023-11-10 09:12 UTC, arunge commented
@mgross Unfortunately, this feature requires a higher version of `elevatr` than we have currently running, that is why the checks fail:
![image](https://github.com/Pandora-IsoMemo/iso-app/assets/16759098/5de114db-380a-43e0-9dd6-b3037e40f407)

Possibly, you need exactly version 0.99.0 of `elevatr`, correct?

I need to discuss with @jan-abel-inwt what way is best for our system to get the higher version into our docker container.
I will update you when we found a solution!

2023-11-10 10:33 UTC, mgross commented
@arunge, I can try with 0.4.2

2023-11-10 10:45 UTC, mgross commented
@arunge ok, it also works for older version

2023-11-16 08:26 UTC, arunge requested changes
- In general, the feature seems to work, I have some minor suggestions.
- However, I tested to create a new _elevation_ map _from scratch_. I did not upload or import any data. After naming the map and pressing _Run_ a progress bar occurs, but nothing seems to happen after that. (The main panel remains empty.)
- Checking "Saved maps" gives a new map, but it looks empty. The thumbnail seems not to be there:
  https://github.com/Pandora-IsoMemo/iso-app/blob/f549072ddfb8bcd9ed7dfc1ac7144c5c41d01c97/R/04-savedMapsModule.R#L43 
  ![image](https://github.com/Pandora-IsoMemo/iso-app/assets/16759098/e6eeccec-c4d8-42c9-90ea-527cfa0ad89d)
- Only after selecting to load the map, the map becomes visible. Could we display the map directly after it was created in the main panel, without having to load the map?
  ![image](https://github.com/Pandora-IsoMemo/iso-app/assets/16759098/886921df-87c9-491c-99bd-66355ab62f0a)
- Additionally, an error occured in some if-clause, could you check and fix this?
  ![image](https://github.com/Pandora-IsoMemo/iso-app/assets/16759098/7589ca7e-c5d9-4118-8c17-b2c911952579)

If you need some assistance regarding the display of the map, please let me know.

2023-11-20 07:47 UTC, arunge approved these changes
Why do you not just remove the code that is not needed for this case?

2023-11-20 07:47 UTC, arunge commented on R/03-mapDiff.R
> +    # }
Please, just remove the comments if this is not needed in this case.

2023-11-20 07:47 UTC, arunge commented on R/03-mapDiff.R
> +    # updateTextInput(session, "saveMapName", value = "")
See above.

2023-12-05 13:59 UTC, arunge commented
@mgross I merged some fixes from the beta into this feature branch. It is just open to remove the comments mentioned above. I could also do this and merge afterwards. Just let me know if you need something. :blush:

2023-12-20 18:39 UTC, merged